server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /shop/assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    location /shop {
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain application/json application/javascript text/css;
}
